C4Context
title Sistema de contexto para um aplicação escolar

Person(Professor, "Professor", "Professor dos alunos")
Person(Aluno, "Aluno","Assiste as aulas e envia tarefas")
Person(Administracao, "Administração", "HR, Diretoria e afins")
System(Sistema, "Sistema de aplicação do colégio", "Permite que os usuarios vejam informações e participem das aulas. Registrando assistindo e compartilhando")

Rel("Professor", "Sistema", "Publica aulas")
Rel("Aluno", "Sistema", "Assiste aulas")
Rel("Administracao", "Sistema", "Administra")
